import type { Resource } from "../types";
import { f, client, order, amount, date, detail, magnitude } from "../fields";
export const logisticaResources: Resource[] = [
  {
    key: "equipment",
    module: "logistica",
    title: "Equipos en custodia",
    singular: "equipo",
    prefix: "EQ",
    description:
      "Identificación, condición física y ubicación de cada instrumento.",
    columns: ["name", "serial", "clientId", "location", "status"],
    states: [
      "Recibido",
      "En laboratorio",
      "En servicio técnico",
      "Listo para entrega",
      "Entregado",
    ],
    fields: [
      f("name", "Descripción del equipo"),
      client,
      f("brand", "Marca"),
      f("model", "Modelo"),
      f("serial", "N.º de serie / código PROMECAL"),
      f("location", "Ubicación", "select", {
        options: [
          "Recepción · A1",
          "Laboratorio eléctrico",
          "Laboratorio de presión",
          "Laboratorio de temperatura",
          "Laboratorio de fotometría",
          "Servicio técnico",
          "Despacho · D1",
          "Cliente",
        ],
      }),
      f(
        "physical",
        "Condición física / golpes, manchas, rajaduras",
        "textarea",
      ),
      detail,
    ],
  },
  {
    key: "receipts",
    module: "logistica",
    title: "Recepción y actas",
    singular: "recepción",
    prefix: "REC",
    description: "Ingreso de equipos con guía de remisión o formato F01.",
    columns: ["name", "orderId", "documentType", "date", "status"],
    states: ["Recibido", "Derivado"],
    fields: [
      f("name", "N.º de guía / F01"),
      order,
      f("documentType", "Documento", "select", {
        options: ["Guía de remisión", "F01-RYD-PR-01"],
      }),
      date,
      f("signedBy", "Conformidad de recepción"),
      detail,
    ],
  },
  {
    key: "dispatches",
    module: "logistica",
    title: "Despachos",
    singular: "despacho",
    prefix: "DES",
    description:
      "Entregas autorizadas desde la orden, sujetas a control financiero.",
    columns: ["name", "orderId", "recipient", "date", "status"],
    readonly: true,
    fields: [
      f("name", "Guía / acta de entrega"),
      order,
      f("recipient", "Responsable del recojo"),
      date,
    ],
  },
  {
    key: "stock",
    module: "logistica",
    title: "Repuestos e insumos",
    singular: "repuesto",
    prefix: "REP",
    description:
      "Disponibilidad y mínimos para la continuidad de los servicios.",
    columns: ["name", "sku", "quantity", "minimum", "cost", "location"],
    fields: [
      f("name", "Repuesto / insumo"),
      f("sku", "Código SKU"),
      f("quantity", "Stock disponible", "number"),
      f("minimum", "Stock mínimo", "number"),
      f("cost", "Costo unitario (S/)", "number"),
      f("location", "Ubicación"),
      detail,
    ],
  },
  {
    key: "movements",
    module: "logistica",
    title: "Movimientos de inventario",
    singular: "movimiento",
    prefix: "MOV",
    description:
      "Entradas y consumos con actualización de existencias y costo por orden.",
    columns: ["name", "stockId", "kind", "quantity", "orderId", "date"],
    immutable: true,
    fields: [
      f("name", "Referencia / motivo"),
      f("stockId", "Repuesto", "select", { ref: "stock" }),
      f("kind", "Movimiento", "select", { options: ["Entrada", "Consumo"] }),
      f("quantity", "Cantidad", "number"),
      f("orderId", "Orden (obligatoria para consumo)", "select", {
        ref: "orders",
        required: false,
      }),
      date,
      detail,
    ],
  },
  {
    key: "suppliers",
    module: "logistica",
    title: "Proveedores",
    singular: "proveedor",
    prefix: "PRV",
    description:
      "Aliados para el abastecimiento y los servicios especializados.",
    columns: ["name", "document", "contact", "email", "status"],
    states: ["Activo", "En evaluación", "Inactivo"],
    fields: [
      f("name", "Razón social"),
      f("document", "RUC"),
      f("contact", "Contacto"),
      f("email", "Correo", "email"),
      f("phone", "Teléfono"),
      detail,
    ],
  },
  {
    key: "purchases",
    module: "logistica",
    title: "Órdenes de compra",
    singular: "orden de compra",
    prefix: "OCP",
    description: "Compras a proveedores vinculadas a necesidades operativas.",
    columns: ["name", "supplierId", "orderId", "amount", "status"],
    states: ["Borrador", "Emitida", "Recibida"],
    fields: [
      f("name", "Concepto de compra"),
      f("supplierId", "Proveedor", "select", { ref: "suppliers" }),
      f("orderId", "Orden de servicio / trabajo", "select", {
        ref: "orders",
        required: false,
      }),
      f("stockId", "Repuesto", "select", { ref: "stock" }),
      f("quantity", "Cantidad", "number"),
      amount,
      f("due", "Entrega prevista", "date"),
      detail,
    ],
  },
];
